### ISSUE TITLE
NAG compiler

### ISSUE THREAD

**Issue by nncarlson** [sgeard/hp#4]
I saw your fortran-lang.discourse.group post.  The NAG compiler (nagfor) can also compile the code and successfully run the test suite once several things are fixed:

1. Explicit kind parameter values, as in `real(8)` are not portable. For example NAG, by default, numbers their kind values sequentially. If you want 8-byte reals, the portable thing to use is `real(real64)` with `real64` imported from the `iso_fortran_env` module.  That said, if the NAG compiler option `-kind=byte` is used the code will work as is.
2. The character lengths in the array constructor `call stack%set_legend(['x:','y:','z:','s','t:'])` are not all the same length. I recall there being a proposal to allow this for an upcoming standard, but I don't believe it is valid in F2018 (I may be mistaken here).
3. The line `is_integer = (index(command,'.') == 0)` invalidly assigns a logical value to an integer. But as this local variable isn't used, simply commenting out that offending line resolves the error.

Also I used this line in the makefile:
```
F_OPTS := -kind=byte -PIC -I $(BUILD_DIR)
```

**Comment by sgeard** [comment]
Thanks for the feedback. I fix the small problems you found and also changed all _real(8)_ to _real(real64)_. I've added a section to the GNUmakefile for _nagfor_ as per your suggestion above but it's untested.
